# Generated by Django 2.0.7 on 2019-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190214_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.CharField(max_length=150),
        ),
    ]
